payloads = {
    "basic": "a12345678",
    "name": "John Doe",
    "firstName": "John",
    "lastName": "Doe",
    "first_name": "John",
    "last_name": "Doe",
    "userName": "Asaf",
    "username": "admin",  
    "user_name": "admin", 
    "user": "admin", 
    "email": "johndoe@example.com",
    "mail": "johndoe@example.com",
    "password": "securepassword123",
    "pass": "securepassword123",
}

tables = [
    'users',
    'orders',
    'products',
    'customers',
    'employees',
    'invoices',
    'payments',
    'categories',
    'messages',
    'reviews',
    'tasks',
    'data',
    'events',
    'articles',
    'contacts',
    'transactions'
    'servers',
    'logs',
    'settings',
    'profiles',
    'accounts',
    'roles',
    'permissions',
    'sessions',
    'tokens',
    'students',
    'teachers',
    'courses',
    'subjects',
    'grades',
    'exams',
    'log_status',
    'employe',
    'employee',
    'employee_status',
    'store',
    'status',
    'status_log',
    'stuff',
]